#!/usr/bin/env ruby
require "net/http"
require "net/http/post/multipart"
require "uri"
require "openssl"
require "json"

# Describe an image using Microsoft's Cognitive Services API:
# https://dev.projectoxford.ai/docs/services/56f91f2d778daf23d8ec6739/operations/56f91f2e778daf14a499e1fa
class Caption
  def initialize
    @url = "https://api.projectoxford.ai"
    @endpoint = "/vision/v1.0/analyze?visualFeatures=Categories,Tags,Description"
    @key = ENV["MS_COGNITIVE_SERVICES_KEY"]
    @uri = URI.parse(@url)
    @http = Net::HTTP.new(@uri.host, @uri.port)
    @http.use_ssl = true
    @http.verify_mode = OpenSSL::SSL::VERIFY_NONE
  end

  def for_url url
    request = Net::HTTP::Post.new(@endpoint)
    request['Ocp-Apim-Subscription-Key'] = @key
    request['Content-Type'] = 'application/json'
    request.body = {"url" => url}.to_json
    send_request request
  end

  def for_file filename
    response = "sdf"
    File.open(filename, "rb") do |image|
      request = Net::HTTP::Post::Multipart.new(@endpoint, {"file" => UploadIO.new(image, 'multipart/form-data', "image")})
      send_request request
    end
  end

  def send_request request
    request['Ocp-Apim-Subscription-Key'] = @key
    response = @http.request(request)
    hash = JSON.parse(response.body)
    hash["description"]["captions"].each do |caption|
      puts "Caption: " + caption["text"]
    end

    categories = hash["categories"].map { |h| h["name"] }
    print "Categories: "
    p categories
  end

  def usage
    puts %{
  USAGE:
    caption [url or path to image file]

    Describes the image
    }
  end

  def run value
    if value
      if value =~ /^http/
        for_url value
      else
        for_file value
      end
    else
      usage
    end
  end
end

Caption.new.run ARGV[0]
